import { Link } from 'react-router-dom';
import { ArrowLeft, FileText, Shield, AlertTriangle, Scale, Users } from 'lucide-react';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#0a0a0a] text-white">
      <div className="fixed inset-0 pointer-events-none">
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[800px] h-[400px] bg-gradient-to-b from-emerald-500/10 via-emerald-500/5 to-transparent rounded-full blur-3xl" />
      </div>

      <nav className="sticky top-0 z-50 border-b border-white/10 bg-[#0a0a0a]/80 backdrop-blur-lg">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between h-16 items-center">
            <Link to="/" className="flex items-center gap-2">
              <img src="/images/logo.png" alt="TextShift" className="h-8 w-auto" />
              <span className="text-white font-medium tracking-wide">TextShift</span>
            </Link>
            <Link to="/" className="flex items-center gap-2 text-gray-400 hover:text-white transition">
              <ArrowLeft className="w-4 h-4" />
              Back to Home
            </Link>
          </div>
        </div>
      </nav>

      <main className="max-w-4xl mx-auto px-4 py-12">
        <div className="mb-8">
          <h1 className="text-3xl md:text-4xl font-light text-white mb-4">Terms and Conditions</h1>
          <p className="text-gray-400">Last updated: February 2026</p>
        </div>

        <div className="space-y-8 text-gray-300">
          <section className="bg-gradient-to-b from-white/5 to-transparent border border-white/10 rounded-2xl p-6">
            <div className="flex items-center gap-3 mb-4">
              <div className="p-2 bg-emerald-500/20 rounded-lg">
                <FileText className="w-5 h-5 text-emerald-400" />
              </div>
              <h2 className="text-xl font-medium text-white">1. Agreement to Terms</h2>
            </div>
            <p className="leading-relaxed mb-4">
              By accessing or using TextShift ("the Service"), you agree to be bound by these Terms and Conditions. 
              If you disagree with any part of these terms, you may not access the Service.
            </p>
            <p className="leading-relaxed">
              TextShift is operated by Sayan Roy Chowdhury, located at 18/1 Banerjee Para Road, West Bengal - 700122, India.
            </p>
          </section>

          <section className="bg-gradient-to-b from-white/5 to-transparent border border-white/10 rounded-2xl p-6">
            <div className="flex items-center gap-3 mb-4">
              <div className="p-2 bg-blue-500/20 rounded-lg">
                <Users className="w-5 h-5 text-blue-400" />
              </div>
              <h2 className="text-xl font-medium text-white">2. User Accounts</h2>
            </div>
            <ul className="list-disc list-inside space-y-3 text-gray-400">
              <li>You must be at least 18 years old to use this Service.</li>
              <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
              <li>You agree to provide accurate and complete information during registration.</li>
              <li>You are responsible for all activities that occur under your account.</li>
              <li>You must notify us immediately of any unauthorized use of your account.</li>
            </ul>
          </section>

          <section className="bg-gradient-to-b from-white/5 to-transparent border border-white/10 rounded-2xl p-6">
            <div className="flex items-center gap-3 mb-4">
              <div className="p-2 bg-purple-500/20 rounded-lg">
                <Shield className="w-5 h-5 text-purple-400" />
              </div>
              <h2 className="text-xl font-medium text-white">3. Service Description</h2>
            </div>
            <p className="leading-relaxed mb-4">
              TextShift provides the following digital services:
            </p>
            <ul className="list-disc list-inside space-y-2 text-gray-400 mb-4">
              <li><strong className="text-white">AI Detection:</strong> Analyzes text to determine if it was generated by AI.</li>
              <li><strong className="text-white">Humanizer:</strong> Transforms AI-generated text to sound more natural and human-like.</li>
              <li><strong className="text-white">Plagiarism Checker:</strong> Scans content against online sources for potential plagiarism.</li>
              <li><strong className="text-white">Writing Tools:</strong> 14 additional tools for grammar, readability, tone adjustment, and more.</li>
            </ul>
            <p className="leading-relaxed">
              We reserve the right to modify, suspend, or discontinue any part of the Service at any time.
            </p>
          </section>

          <section className="bg-gradient-to-b from-white/5 to-transparent border border-white/10 rounded-2xl p-6">
            <div className="flex items-center gap-3 mb-4">
              <div className="p-2 bg-amber-500/20 rounded-lg">
                <Scale className="w-5 h-5 text-amber-400" />
              </div>
              <h2 className="text-xl font-medium text-white">4. Subscription Plans & Payments</h2>
            </div>
            <ul className="list-disc list-inside space-y-3 text-gray-400">
              <li><strong className="text-white">Free Plan:</strong> 5,000 words/month for AI Detection only.</li>
              <li><strong className="text-white">Starter Plan ($9/month):</strong> 50,000 words/month for all tools.</li>
              <li><strong className="text-white">Pro Plan ($19/month):</strong> Unlimited words for all tools.</li>
              <li><strong className="text-white">Enterprise Plan ($49/month):</strong> Unlimited words plus API access and priority support.</li>
              <li>All payments are processed securely through Razorpay.</li>
              <li>Prices are in USD and may be subject to applicable taxes.</li>
              <li>Credits purchased never expire.</li>
            </ul>
          </section>

          <section className="bg-gradient-to-b from-white/5 to-transparent border border-white/10 rounded-2xl p-6">
            <div className="flex items-center gap-3 mb-4">
              <div className="p-2 bg-rose-500/20 rounded-lg">
                <AlertTriangle className="w-5 h-5 text-rose-400" />
              </div>
              <h2 className="text-xl font-medium text-white">5. Prohibited Uses</h2>
            </div>
            <p className="leading-relaxed mb-4">You agree not to use the Service to:</p>
            <ul className="list-disc list-inside space-y-2 text-gray-400">
              <li>Violate any applicable laws or regulations.</li>
              <li>Infringe on intellectual property rights of others.</li>
              <li>Submit content that is illegal, harmful, or offensive.</li>
              <li>Attempt to gain unauthorized access to our systems.</li>
              <li>Use automated systems to access the Service without permission.</li>
              <li>Resell or redistribute our services without authorization.</li>
              <li>Engage in academic dishonesty or fraud.</li>
            </ul>
          </section>

          <section className="bg-gradient-to-b from-white/5 to-transparent border border-white/10 rounded-2xl p-6">
            <h2 className="text-xl font-medium text-white mb-4">6. Intellectual Property</h2>
            <p className="leading-relaxed mb-4">
              The Service and its original content, features, and functionality are owned by TextShift and are 
              protected by international copyright, trademark, and other intellectual property laws.
            </p>
            <p className="leading-relaxed">
              You retain ownership of any content you submit to the Service. By using our Service, you grant us 
              a limited license to process your content solely for the purpose of providing the Service.
            </p>
          </section>

          <section className="bg-gradient-to-b from-white/5 to-transparent border border-white/10 rounded-2xl p-6">
            <h2 className="text-xl font-medium text-white mb-4">7. Disclaimer of Warranties</h2>
            <p className="leading-relaxed mb-4">
              The Service is provided "as is" and "as available" without warranties of any kind, either express 
              or implied. We do not guarantee that:
            </p>
            <ul className="list-disc list-inside space-y-2 text-gray-400">
              <li>The Service will be uninterrupted or error-free.</li>
              <li>Results from the Service will be 100% accurate.</li>
              <li>The Service will meet your specific requirements.</li>
            </ul>
          </section>

          <section className="bg-gradient-to-b from-white/5 to-transparent border border-white/10 rounded-2xl p-6">
            <h2 className="text-xl font-medium text-white mb-4">8. Limitation of Liability</h2>
            <p className="leading-relaxed">
              To the maximum extent permitted by law, TextShift shall not be liable for any indirect, incidental, 
              special, consequential, or punitive damages, including loss of profits, data, or other intangible 
              losses resulting from your use of the Service.
            </p>
          </section>

          <section className="bg-gradient-to-b from-white/5 to-transparent border border-white/10 rounded-2xl p-6">
            <h2 className="text-xl font-medium text-white mb-4">9. Governing Law</h2>
            <p className="leading-relaxed">
              These Terms shall be governed by and construed in accordance with the laws of India, without regard 
              to its conflict of law provisions. Any disputes arising from these Terms shall be subject to the 
              exclusive jurisdiction of the courts in West Bengal, India.
            </p>
          </section>

          <section className="bg-gradient-to-b from-white/5 to-transparent border border-white/10 rounded-2xl p-6">
            <h2 className="text-xl font-medium text-white mb-4">10. Changes to Terms</h2>
            <p className="leading-relaxed">
              We reserve the right to modify these Terms at any time. We will notify users of any material changes 
              by posting the new Terms on this page and updating the "Last updated" date. Your continued use of 
              the Service after such modifications constitutes acceptance of the updated Terms.
            </p>
          </section>

          <section className="bg-gradient-to-b from-white/5 to-transparent border border-white/10 rounded-2xl p-6">
            <h2 className="text-xl font-medium text-white mb-4">11. Contact Information</h2>
            <p className="leading-relaxed mb-4">
              For any questions about these Terms, please contact us:
            </p>
            <div className="space-y-2 text-gray-400">
              <p><strong className="text-white">Company:</strong> TextShift</p>
              <p><strong className="text-white">Founder:</strong> Sayan Roy Chowdhury</p>
              <p><strong className="text-white">Address:</strong> 18/1 Banerjee Para Road, West Bengal - 700122, India</p>
              <p><strong className="text-white">Email:</strong> legal@textshift.org</p>
            </div>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-white/10">
          <div className="flex flex-wrap gap-4 text-sm text-gray-400">
            <Link to="/privacy-policy" className="hover:text-white transition">Privacy Policy</Link>
            <Link to="/shipping-policy" className="hover:text-white transition">Shipping Policy</Link>
            <Link to="/refund-policy" className="hover:text-white transition">Refund Policy</Link>
            <Link to="/contact" className="hover:text-white transition">Contact Us</Link>
          </div>
        </div>
      </main>
    </div>
  );
}
