"use client";

import { useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { useLanguage } from "@/lib/i18n/LanguageContext";
import {
  Download,
  Share2,
  Instagram,
  Twitter,
  Facebook,
  Copy,
  Check,
  Sparkles,
} from "lucide-react";

interface ShareableCardProps {
  title: string;
  subtitle?: string;
  mainContent: React.ReactNode;
  footerContent?: React.ReactNode;
  gradient?: "amber" | "purple" | "blue" | "green" | "pink";
  zodiacSign?: string;
  showBranding?: boolean;
}

const gradientClasses = {
  amber: "from-amber-500 via-orange-500 to-red-500",
  purple: "from-purple-500 via-pink-500 to-rose-500",
  blue: "from-blue-500 via-cyan-500 to-teal-500",
  green: "from-green-500 via-emerald-500 to-teal-500",
  pink: "from-pink-500 via-rose-500 to-red-500",
};

const zodiacEmojis: Record<string, string> = {
  Aries: "♈",
  Taurus: "♉",
  Gemini: "♊",
  Cancer: "♋",
  Leo: "♌",
  Virgo: "♍",
  Libra: "♎",
  Scorpio: "♏",
  Sagittarius: "♐",
  Capricorn: "♑",
  Aquarius: "♒",
  Pisces: "♓",
};

export function ShareableCard({
  title,
  subtitle,
  mainContent,
  footerContent,
  gradient = "amber",
  zodiacSign,
  showBranding = true,
}: ShareableCardProps) {
  const { t } = useLanguage();
  const cardRef = useRef<HTMLDivElement>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [copied, setCopied] = useState(false);
  const [showShareMenu, setShowShareMenu] = useState(false);

  const generateImage = async (): Promise<string | null> => {
    if (!cardRef.current) return null;
    
    setIsGenerating(true);
    try {
      const html2canvas = (await import("html2canvas")).default;
      const canvas = await html2canvas(cardRef.current, {
        scale: 2,
        backgroundColor: null,
        useCORS: true,
      });
      return canvas.toDataURL("image/png");
    } catch (error) {
      console.error("Error generating image:", error);
      return null;
    } finally {
      setIsGenerating(false);
    }
  };

  const handleDownload = async () => {
    const imageData = await generateImage();
    if (imageData) {
      const link = document.createElement("a");
      link.download = `vedicstarastro-${title.toLowerCase().replace(/\s+/g, "-")}.png`;
      link.href = imageData;
      link.click();
    }
  };

  const handleCopyImage = async () => {
    const imageData = await generateImage();
    if (imageData) {
      try {
        const response = await fetch(imageData);
        const blob = await response.blob();
        await navigator.clipboard.write([
          new ClipboardItem({ "image/png": blob }),
        ]);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      } catch (error) {
        console.error("Error copying image:", error);
      }
    }
  };

  const handleShare = async (platform: "instagram" | "twitter" | "facebook" | "native") => {
    const imageData = await generateImage();
    const shareText = `${title}${subtitle ? ` - ${subtitle}` : ""}\n\nGenerated by VedicStarAstro.com`;
    const shareUrl = window.location.href;

    if (platform === "native" && navigator.share) {
      try {
        if (imageData) {
          const response = await fetch(imageData);
          const blob = await response.blob();
          const file = new File([blob], "horoscope.png", { type: "image/png" });
          await navigator.share({
            title: title,
            text: shareText,
            url: shareUrl,
            files: [file],
          });
        } else {
          await navigator.share({
            title: title,
            text: shareText,
            url: shareUrl,
          });
        }
      } catch (error) {
        console.error("Error sharing:", error);
      }
    } else if (platform === "twitter") {
      const twitterUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(shareText)}&url=${encodeURIComponent(shareUrl)}`;
      window.open(twitterUrl, "_blank");
    } else if (platform === "facebook") {
      const facebookUrl = `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(shareUrl)}&quote=${encodeURIComponent(shareText)}`;
      window.open(facebookUrl, "_blank");
    } else if (platform === "instagram") {
      await handleDownload();
      alert(t("share.instagramInstructions", "Image downloaded! Open Instagram and share from your gallery."));
    }
    
    setShowShareMenu(false);
  };

  return (
    <div className="space-y-4">
      <div
        ref={cardRef}
        className={`relative overflow-hidden rounded-2xl bg-gradient-to-br ${gradientClasses[gradient]} p-1`}
        style={{ aspectRatio: "1/1", maxWidth: "400px" }}
      >
        <div className="h-full w-full rounded-xl bg-white/95 backdrop-blur-sm p-6 flex flex-col">
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-2">
              {zodiacSign && (
                <span className="text-3xl">{zodiacEmojis[zodiacSign] || "✨"}</span>
              )}
              <div>
                <h3 className="font-bold text-gray-900 text-lg">{title}</h3>
                {subtitle && (
                  <p className="text-sm text-gray-600">{subtitle}</p>
                )}
              </div>
            </div>
            <Sparkles className="w-6 h-6 text-amber-500" />
          </div>

          <div className="flex-1 flex items-center justify-center">
            {mainContent}
          </div>

          {footerContent && (
            <div className="mt-4 pt-4 border-t border-gray-200">
              {footerContent}
            </div>
          )}

          {showBranding && (
            <div className="mt-4 flex items-center justify-center gap-2 text-xs text-gray-500">
              <span className="font-semibold text-amber-600">VedicStarAstro</span>
              <span>•</span>
              <span>{t("share.authenticVedicAstrology", "Authentic Vedic Astrology")}</span>
            </div>
          )}
        </div>
      </div>

      <div className="flex flex-wrap gap-2 justify-center">
        <Button
          size="sm"
          variant="outline"
          onClick={handleDownload}
          disabled={isGenerating}
          className="gap-2"
        >
          <Download className="w-4 h-4" />
          {isGenerating ? t("share.generating", "Generating...") : t("share.download", "Download")}
        </Button>

        <Button
          size="sm"
          variant="outline"
          onClick={handleCopyImage}
          disabled={isGenerating}
          className="gap-2"
        >
          {copied ? (
            <>
              <Check className="w-4 h-4 text-green-500" />
              {t("share.copied", "Copied!")}
            </>
          ) : (
            <>
              <Copy className="w-4 h-4" />
              {t("share.copyImage", "Copy Image")}
            </>
          )}
        </Button>

        <div className="relative">
          <Button
            size="sm"
            variant="outline"
            onClick={() => setShowShareMenu(!showShareMenu)}
            className="gap-2"
          >
            <Share2 className="w-4 h-4" />
            {t("share.share", "Share")}
          </Button>

          {showShareMenu && (
            <div className="absolute top-full mt-2 right-0 bg-white rounded-lg shadow-lg border p-2 z-50 min-w-[150px]">
              <button
                onClick={() => handleShare("native")}
                className="w-full flex items-center gap-2 px-3 py-2 hover:bg-gray-100 rounded-md text-sm"
              >
                <Share2 className="w-4 h-4" />
                {t("share.shareNative", "Share...")}
              </button>
              <button
                onClick={() => handleShare("instagram")}
                className="w-full flex items-center gap-2 px-3 py-2 hover:bg-gray-100 rounded-md text-sm"
              >
                <Instagram className="w-4 h-4 text-pink-500" />
                Instagram
              </button>
              <button
                onClick={() => handleShare("twitter")}
                className="w-full flex items-center gap-2 px-3 py-2 hover:bg-gray-100 rounded-md text-sm"
              >
                <Twitter className="w-4 h-4 text-blue-400" />
                Twitter/X
              </button>
              <button
                onClick={() => handleShare("facebook")}
                className="w-full flex items-center gap-2 px-3 py-2 hover:bg-gray-100 rounded-md text-sm"
              >
                <Facebook className="w-4 h-4 text-blue-600" />
                Facebook
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

export function HoroscopeShareCard({
  zodiacSign,
  prediction,
  date,
  luckyNumber,
  luckyColor,
}: {
  zodiacSign: string;
  prediction: string;
  date: string;
  luckyNumber?: string;
  luckyColor?: string;
}) {
  const { t } = useLanguage();

  return (
    <ShareableCard
      title={zodiacSign}
      subtitle={date}
      zodiacSign={zodiacSign}
      gradient="purple"
      mainContent={
        <div className="text-center px-4">
          <p className="text-gray-700 text-sm leading-relaxed line-clamp-6">
            {prediction}
          </p>
        </div>
      }
      footerContent={
        <div className="flex justify-center gap-6 text-sm">
          {luckyNumber && (
            <div className="text-center">
              <p className="text-gray-500">{t("share.luckyNumber", "Lucky Number")}</p>
              <p className="font-bold text-purple-600">{luckyNumber}</p>
            </div>
          )}
          {luckyColor && (
            <div className="text-center">
              <p className="text-gray-500">{t("share.luckyColor", "Lucky Color")}</p>
              <p className="font-bold text-purple-600">{luckyColor}</p>
            </div>
          )}
        </div>
      }
    />
  );
}

export function CompatibilityShareCard({
  sign1,
  sign2,
  compatibilityScore,
  summary,
}: {
  sign1: string;
  sign2: string;
  compatibilityScore: number;
  summary: string;
}) {
  const { t } = useLanguage();

  return (
    <ShareableCard
      title={`${sign1} & ${sign2}`}
      subtitle={t("share.loveCompatibility", "Love Compatibility")}
      gradient="pink"
      mainContent={
        <div className="text-center">
          <div className="flex items-center justify-center gap-4 mb-4">
            <span className="text-4xl">{zodiacEmojis[sign1] || "✨"}</span>
            <span className="text-2xl text-pink-500">❤️</span>
            <span className="text-4xl">{zodiacEmojis[sign2] || "✨"}</span>
          </div>
          <div className="text-5xl font-bold text-pink-600 mb-2">
            {compatibilityScore}%
          </div>
          <p className="text-gray-600 text-sm">{summary}</p>
        </div>
      }
    />
  );
}

export function KundliShareCard({
  name,
  ascendant,
  moonSign,
  sunSign,
  nakshatra,
}: {
  name: string;
  ascendant: string;
  moonSign: string;
  sunSign: string;
  nakshatra: string;
}) {
  const { t } = useLanguage();

  return (
    <ShareableCard
      title={name}
      subtitle={t("share.birthChart", "Birth Chart")}
      zodiacSign={moonSign}
      gradient="amber"
      mainContent={
        <div className="grid grid-cols-2 gap-4 w-full">
          <div className="text-center p-3 bg-amber-50 rounded-lg">
            <p className="text-xs text-gray-500">{t("share.ascendant", "Ascendant")}</p>
            <p className="font-bold text-amber-700">{ascendant}</p>
          </div>
          <div className="text-center p-3 bg-amber-50 rounded-lg">
            <p className="text-xs text-gray-500">{t("share.moonSign", "Moon Sign")}</p>
            <p className="font-bold text-amber-700">{moonSign}</p>
          </div>
          <div className="text-center p-3 bg-amber-50 rounded-lg">
            <p className="text-xs text-gray-500">{t("share.sunSign", "Sun Sign")}</p>
            <p className="font-bold text-amber-700">{sunSign}</p>
          </div>
          <div className="text-center p-3 bg-amber-50 rounded-lg">
            <p className="text-xs text-gray-500">{t("share.nakshatra", "Nakshatra")}</p>
            <p className="font-bold text-amber-700">{nakshatra}</p>
          </div>
        </div>
      }
    />
  );
}

export function TransitShareCard({
  planet,
  sign,
  effect,
  advice,
}: {
  planet: string;
  sign: string;
  effect: "Favorable" | "Challenging" | "Mixed";
  advice: string;
}) {
  const { t } = useLanguage();
  
  const effectColors = {
    Favorable: "text-green-600 bg-green-50",
    Challenging: "text-red-600 bg-red-50",
    Mixed: "text-amber-600 bg-amber-50",
  };

  return (
    <ShareableCard
      title={`${planet} ${t("share.transit", "Transit")}`}
      subtitle={`${t("share.in", "in")} ${sign}`}
      gradient="blue"
      mainContent={
        <div className="text-center w-full">
          <div className={`inline-block px-4 py-2 rounded-full text-sm font-medium mb-4 ${effectColors[effect]}`}>
            {t(`share.effect.${effect.toLowerCase()}`, effect)}
          </div>
          <p className="text-gray-700 text-sm leading-relaxed">
            {advice}
          </p>
        </div>
      }
    />
  );
}
